import { useEffect, useState } from 'react'
import { ArrowDown, ArrowUpRight, BriefcaseBusiness, Code2, ExternalLink, Github, GraduationCap, Mail, Menu, Sparkles, X } from 'lucide-react'
import { navItems, projects, skills } from './data'

const email = 'Okorietochukwu51@gmail.com'
const githubUrl = 'https://github.com/TEEKAY-alt403'

function Heading({ n, label, title, text }: { n: string; label: string; title: string; text?: string }) {
  return <div className="mb-12 max-w-3xl"><p className="mb-3 text-xs font-bold uppercase tracking-[.25em] text-indigo-400">{n} — {label}</p><h2 className="text-4xl font-black tracking-tight sm:text-5xl">{title}</h2>{text && <p className="mt-5 text-lg leading-8 text-zinc-400">{text}</p>}</div>
}

function App() {
  const [menuOpen, setMenuOpen] = useState(false)
  useEffect(() => { document.body.classList.toggle('menu-open', menuOpen); return () => document.body.classList.remove('menu-open') }, [menuOpen])
  useEffect(() => { const f = (e: KeyboardEvent) => e.key === 'Escape' && setMenuOpen(false); window.addEventListener('keydown', f); return () => window.removeEventListener('keydown', f) }, [])
  const close = () => setMenuOpen(false)
  const focus = 'rounded-md focus-visible:outline focus-visible:outline-2 focus-visible:outline-indigo-400'

  return <div className="min-h-screen overflow-x-hidden bg-[#08090c] text-zinc-100">
    <header className="fixed inset-x-0 top-0 z-50 border-b border-white/5 bg-[#08090c]/80 backdrop-blur-xl"><nav className="mx-auto flex max-w-6xl items-center justify-between px-5 py-4 lg:px-8" aria-label="Main navigation">
      <a href="#home" onClick={close} className={`${focus} text-lg font-black tracking-tight`}>OTS<span className="text-indigo-400">.</span></a>
      <div className="hidden items-center gap-7 text-sm text-zinc-400 md:flex">{navItems.map(item => <a key={item} href={`#${item.toLowerCase()}`} className={`${focus} transition hover:text-white`}>{item}</a>)}</div>
      <a href={`mailto:${email}`} className="hidden rounded-full bg-white px-5 py-2 text-sm font-semibold text-black transition hover:bg-zinc-200 md:block">Let's talk</a>
      <button onClick={() => setMenuOpen(v => !v)} className={`${focus} p-2 md:hidden`} aria-label={menuOpen ? 'Close navigation' : 'Open navigation'} aria-expanded={menuOpen} aria-controls="mobile-navigation">{menuOpen ? <X size={22}/> : <Menu size={22}/>}</button>
    </nav><div id="mobile-navigation" hidden={!menuOpen} className="border-t border-white/5 px-5 pb-5 md:hidden">{navItems.map(item => <a key={item} href={`#${item.toLowerCase()}`} onClick={close} className={`${focus} block py-3 text-zinc-300`}>{item}</a>)}</div></header>

    <main>
      <section id="home" className="grid-bg relative flex min-h-screen items-center px-5 pt-24 lg:px-8"><div className="absolute left-1/2 top-1/3 h-80 w-80 -translate-x-1/2 rounded-full bg-indigo-500/10 blur-[120px]" aria-hidden="true"/><div className="mx-auto grid w-full max-w-6xl gap-12 py-20 lg:grid-cols-[1.2fr_.8fr] lg:items-center"><div className="relative z-10"><div className="mb-6 inline-flex items-center gap-2 rounded-full border border-white/10 bg-white/[.03] px-4 py-2 text-sm text-zinc-300"><span className="h-2 w-2 rounded-full bg-emerald-400"/>Open to opportunities</div><p className="mb-4 text-sm font-bold uppercase tracking-[.25em] text-indigo-400">Frontend Developer</p><h1 className="max-w-4xl text-5xl font-black leading-[.95] tracking-[-.05em] sm:text-7xl lg:text-8xl">I’m <span className="text-zinc-500">Okorie Tochukwu Solomon.</span><br/>I build digital experiences that feel right.</h1><p className="mt-8 max-w-2xl text-lg leading-8 text-zinc-400">A Computer Science student and frontend developer focused on building responsive, accessible React interfaces and useful digital products.</p><div className="mt-10 flex flex-wrap gap-3"><a href="#projects" className="inline-flex items-center gap-2 rounded-full bg-indigo-500 px-6 py-3 font-semibold transition hover:bg-indigo-400 focus-visible:outline focus-visible:outline-2 focus-visible:outline-indigo-300">View my work <ArrowDown size={17}/></a><a href={`mailto:${email}`} className="inline-flex items-center gap-2 rounded-full border border-white/10 px-6 py-3 font-semibold transition hover:bg-white/5 ${focus}">Get in touch <ArrowUpRight size={17}/></a></div><div className="mt-8 flex flex-wrap gap-5 text-sm text-zinc-500"><span>React</span><span>TypeScript</span><span>JavaScript</span><span>Responsive UI</span></div></div><div className="relative hidden justify-center lg:flex" aria-hidden="true"><div className="animate-float relative flex h-80 w-80 items-center justify-center rounded-[2rem] border border-white/10 bg-white/[.03] shadow-2xl shadow-indigo-950/40"><div className="absolute inset-5 rounded-[1.5rem] border border-indigo-400/20"/><Code2 size={92} strokeWidth={1} className="text-indigo-300"/><span className="absolute bottom-8 text-xs uppercase tracking-[.35em] text-zinc-500">Build • Learn • Ship</span></div></div></div></section>

      <section id="about" className="border-t border-white/5 px-5 py-28 lg:px-8"><div className="mx-auto max-w-6xl"><Heading n="01" label="About" title="Curious by nature. Serious about craft."/><div className="grid gap-10 lg:grid-cols-2"><div className="rounded-3xl border border-indigo-400/15 bg-indigo-500/[.04] p-8"><p className="text-2xl font-semibold leading-10">I enjoy the space where design and engineering meet — taking a rough idea, understanding the user behind it, and building an interface that is useful, clear and memorable.</p></div><div className="space-y-5 text-lg leading-8 text-zinc-400"><p>My Computer Science background gives me a strong technical foundation, while hands-on projects keep me learning modern frontend patterns, deployment workflows and practical product development.</p><p>I’m especially interested in opportunities where I can contribute to a real product, learn from experienced developers and keep improving as an engineer.</p></div></div></div></section>

      <section id="skills" className="border-t border-white/5 bg-white/[.015] px-5 py-28 lg:px-8"><div className="mx-auto max-w-6xl"><Heading n="02" label="Skills" title="A practical frontend toolkit." text="Tools I use to turn designs and ideas into responsive, maintainable interfaces."/><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{skills.map(skill => <div key={skill.name} className="rounded-2xl border border-white/8 bg-[#0d0f14] p-5 transition hover:-translate-y-1 hover:border-indigo-400/30"><p className="text-xs font-semibold uppercase tracking-[.18em] text-zinc-600">{skill.group}</p><p className="mt-2 font-medium">{skill.name}</p></div>)}</div></div></section>

      <section id="projects" className="border-t border-white/5 px-5 py-28 lg:px-8"><div className="mx-auto max-w-6xl"><div className="flex items-end justify-between gap-6"><Heading n="03" label="Projects" title="Selected work." text="A focused selection of practical work. Finished projects are better evidence than placeholder cards."/><Sparkles className="mb-2 hidden text-indigo-400 sm:block" aria-hidden="true"/></div><div className="grid gap-5 lg:grid-cols-2">{projects.map((project, i) => <article key={project.title} className="group flex min-h-[390px] flex-col rounded-3xl border border-white/8 bg-[#0d0f14] p-7 transition duration-300 hover:-translate-y-2 hover:border-indigo-400/30"><div className="flex items-center justify-between text-xs font-semibold uppercase tracking-[.2em] text-zinc-500"><span>0{i+1}</span><span>{project.type}</span></div><div className="mt-12 flex-1"><h3 className="text-2xl font-bold">{project.title}</h3><p className="mt-4 max-w-xl leading-7 text-zinc-400">{project.description}</p></div><div className="flex flex-wrap gap-2">{project.stack.map(item => <span key={item} className="rounded-full bg-white/5 px-3 py-1 text-xs text-zinc-400">{item}</span>)}</div>{project.href ? <a href={project.href} target="_blank" rel="noopener noreferrer" className={`${focus} mt-6 inline-flex w-fit items-center gap-2 text-sm font-semibold text-indigo-300`}>View on GitHub <ExternalLink size={16}/></a> : <span className="mt-6 inline-flex w-fit rounded-full border border-dashed border-white/10 px-4 py-2 text-sm text-zinc-600">{project.status ?? 'In development'}</span>}</article>)}</div></div></section>

      <section id="experience" className="border-t border-white/5 bg-white/[.015] px-5 py-28 lg:px-8"><div className="mx-auto max-w-6xl"><Heading n="04" label="Experience & Education" title="Building the foundation for a career in software."/><div className="grid gap-5 lg:grid-cols-2"><article className="rounded-3xl border border-white/8 bg-[#0d0f14] p-8"><BriefcaseBusiness className="mb-7 text-indigo-400"/><h3 className="text-2xl font-bold">SIWES — Teebiz Technologies Limited</h3><p className="mt-2 text-sm text-zinc-500">Industrial Training • 2026</p><p className="mt-6 leading-7 text-zinc-400">Hands-on exposure to professional software development workflows, web technologies and practical technology projects as part of my industrial training.</p></article><article className="rounded-3xl border border-white/8 bg-[#0d0f14] p-8"><GraduationCap className="mb-7 text-indigo-400"/><h3 className="text-2xl font-bold">Computer Science</h3><p className="mt-2 text-sm text-zinc-500">Vision University • Undergraduate</p><p className="mt-6 leading-7 text-zinc-400">Building a broad foundation across programming, data structures, software development, computer architecture, databases, networking and modern computing.</p></article></div></div></section>

      <section id="contact" className="border-t border-white/5 px-5 py-28 lg:px-8"><div className="mx-auto max-w-6xl rounded-[2rem] border border-indigo-400/20 bg-gradient-to-br from-indigo-500/10 to-transparent p-8 sm:p-14"><p className="mb-3 text-xs font-bold uppercase tracking-[.25em] text-indigo-400">05 — Contact</p><h2 className="max-w-3xl text-4xl font-black tracking-tight sm:text-6xl">Have an idea worth building?</h2><p className="mt-6 max-w-2xl text-lg leading-8 text-zinc-400">I’m open to internships, freelance opportunities, collaborations and interesting frontend projects.</p><div className="mt-8 flex flex-wrap gap-3"><a href={githubUrl} target="_blank" rel="noopener noreferrer" className="inline-flex items-center gap-2 rounded-full bg-white px-6 py-3 font-semibold text-black"> <Github size={17}/>GitHub</a><a href={`mailto:${email}`} className="inline-flex items-center gap-2 rounded-full border border-white/10 px-6 py-3 font-semibold"><Mail size={17}/>Email me</a></div></div></section>
    </main>
    <footer className="border-t border-white/5 px-5 py-8 lg:px-8"><div className="mx-auto flex max-w-6xl justify-between gap-5 text-sm text-zinc-500"><p>© {new Date().getFullYear()} Okorie Tochukwu Solomon. Built with React.</p><a href={githubUrl} target="_blank" rel="noopener noreferrer" aria-label="Open GitHub profile" className={focus}><Github size={19}/></a></div></footer>
  </div>
}
export default App
